---
title: "R Notebook"
output: html_notebook
---

```{r, setup}
knitr::opts_knit$set(root.dir = "")
```


```{r, functions}
make_K<-function(rootname){
  main<-readGRM(rootname)
  main_K=matrix(0,max(main$grm$id1),max(main$grm$id2))
  main_K[upper.tri(main_K,diag=T)]=main$grm$grm
  main_K[lower.tri(main_K)]=t(main_K)[lower.tri(main_K)]
  return(main_K)
}

normalize_kinmat <- function(kinmat){
  #normalize kinship so that Kij \in [0,1]
  tmp=kinmat - min(kinmat)
  tmp=tmp/max(tmp)
  #fix eigenvalues to positive
  diag(tmp)=diag(tmp)-min(eigen(tmp)$values)
  return(tmp)
}


readGRM <- function(rootname)
{
  bin.file.name <- paste(rootname, ".grm.bin", sep="")
  n.file.name <- paste(rootname, ".grm.N.bin", sep="")
  id.file.name <- paste(rootname, ".grm.id", sep="")
  
  cat("Reading IDs\n")
  id <- read.table(id.file.name, colClasses="character")
  n <- dim(id)[1]
  cat("Reading GRM\n")
  bin.file <- file(bin.file.name, "rb")
  grm <- readBin(bin.file, n=n*(n+1)/2, what=numeric(0), size=4)
  close(bin.file)
  cat("Reading N\n")
  n.file <- file(n.file.name, "rb")
  N <- readBin(n.file, n=n*(n+1)/2, what=numeric(0), size=4)
  close(n.file)
  
  cat("Creating data frame\n")
  l <- list()
  for(i in 1:n)
  {
    l[[i]] <- 1:i
  }
  col1 <- rep(1:n, 1:n)
  col2 <- unlist(l)
  grm <- data.frame(id1=col1, id2=col2, N=N, grm=grm)	
  
  ret <- list()
  ret$grm <- grm
  ret$id <- id
  return(ret)
}
```


```{r}
library("tidyverse")
```

```{r}
mex_K<-make_K("~/Desktop/mex_origin_paper/ldak/standard.elai") 
smex_K<-svd(mex_K)

rest_K<-make_K("~/Desktop/mex_origin_paper/ldak/standard.geno") 
srest_K<-svd(rest_K)
```

```{r}
for(rnd in 1:10){
# Two K matrices plus residuals
cmex_K = sqrt(smex_K$d) * t(smex_K$u) # chol(moa_K)
crest_K = sqrt(srest_K$d) * t(srest_K$u) 
# create 4 vectors of random variables with each kinship matrix (or uncorrelated residuals)
U = matrix(0,nrow = nrow(cmex_K),ncol = 3)
U[,1] = crossprod(cmex_K,rnorm(nrow(cmex_K)))
U[,2] = crossprod(crest_K,rnorm(nrow(crest_K)))
U[,3] = rnorm(nrow(cmex_K))
# Create a grid of variance component proportions for the 4 variance components
#grid = seq(0,1,by = 0.2)
#h2s = expand.grid(h21 = grid,h22 = grid,h23 = grid)
#h2s$h24 = 1-rowSums(h2s)
#h2s = h2s[h2s$h24 > 0,]

# If we want very specific variance component proportions to test
#Total h2 should be c(rep(0.2,4), rep(0.5,4),rep(0.8,4))
#mex h2 should be x% of the total where x is rep(c(0.1,0.25,0.5,0.75),3)
#rest h2 should be the inverse of mex h2
h2s = tibble(h21 = c(0.02,0.05,0.10,0.15,0.05,0.125,0.25,0.375,0.08,0.2,0.4,0.6), #h2 for mex
             h22 = c(0.18,0.15,0.1,0.05,0.45,0.375,0.25,0.125,0.72,0.6,0.4,0.2) #h2 for rest
             )
h2s$h23 = 1-rowSums(h2s) #h2 for error
# for each row of h2s, create a y by re-weighting the vectors of random variables
Y = U %*% t(sqrt(h2s))
apply(Y,2,sd)
# column i of Y is a trait with variance component proportions h2s[i,]
colnames(Y)<- c(paste("Set",1:12,"-",rnd,sep = ""))
if(rnd == 1){ #iteratively adds the new trait to a main dataframe
  Sim_Traits = as.data.frame(Y) } else{
    Sim_Traits = add_column(Sim_Traits, 
                            Y[,1], Y[,2],Y[,3],Y[,4],
                            Y[,5], Y[,6],Y[,7],Y[,8],
                            Y[,9], Y[,10],Y[,11],Y[,12])
    colnames(Sim_Traits)[(ncol(Sim_Traits)-11):ncol(Sim_Traits)] = colnames(Y) #changes the column names from "Y" to trait name
  }
}
write_tsv(Sim_Traits, paste("~/Desktop/Simulated_Phenotypes",".","Round1",".txt",sep = ""))
```
Write Y as the phenotype output file (if not doing the loop)
```{r}
colnames(Y)<- c(paste("Set",1:4,"-","1",sep = ""))
write_tsv(as.data.frame(Y), paste("Simulated_Phenotypes",".1",".txt",sep = ""))
```

#And to find the correlation between two kinship matrices
```{r}
cor(c(mex_K),c(rest_K))
```